Rotate the project nginx log by logrotate
juwai/ansible-role-laravel pull request #4
Opened 2017-01-09 04:43 UTC by mark-juwai

## Summary of changes

- _Code/resources that have been added, updated or removed. Please provide rationale for changes whenever applicable_

## How to Test

- `$ cd tests`
- `$ vagrant up`
- `$ vagrant ssh`
- `$ less /etc/logrotate.d/test`
- `$ sudo logrotate /etc/logrotate.d/test -d -f`

@tjoelsson Who else can I assign the PR to? There are few assignees for this repo.

2017-01-09 05:41 UTC, tjoelsson requested changes

2017-01-09 05:41 UTC, tjoelsson commented on meta/main.yml
> +  - role: retr0h.logrotate
You can make this a conditional dependency

2017-01-09 05:41 UTC, tjoelsson commented on tasks/main.yml
> +      - 'rotate 14'
CNC said they wanted weekly retention

2017-01-09 05:41 UTC, tjoelsson commented on defaults/main.yml
> +laravel_log_rotate: true
Should specify it means nginx log, not application log. How about `laravel_rotate_nginx_log`?

2017-01-09 06:49 UTC, mark-juwai commented on meta/main.yml
> +  - role: retr0h.logrotate
```
dependencies:
  - { role: retr0h.logrotate, when: laravel_rotate_nginx_log }
```
Is this what you want? If yes, how we set the variable when downloading the role?

2017-01-09 06:59 UTC, tjoelsson commented on tasks/main.yml
> +      - 'rotate 14'
Sorry, I just checked the web servers. We have 30 days for juwai.com. Should probably keep the same. Maybe it's best to create a variable for this.

2017-01-09 07:01 UTC, tjoelsson commented on meta/main.yml
> +  - role: retr0h.logrotate
I think download will always happen

2017-01-09 07:02 UTC, tjoelsson commented on tasks/main.yml
> +      - 'rotate 7'
Let's create a variable for this, with 30 days as default

2017-01-09 07:56 UTC, mark-juwai commented
@tjoelsson Comments addressed, please check again. Thank you.

2017-01-09 09:02 UTC, tjoelsson approved these changes

2017-01-10 06:28 UTC, mark-juwai commented
@upbeta01 Please review when you get time. Thanks.

2017-01-10 12:04 UTC, upbeta01 commented on tasks/main.yml
> +    path: '/var/log/nginx/{{ application_name }}/*.log'
Not sure if it's a good idea a wildcard on the line. Though, we wanted to apply log rotate to any log file.
Would it be cool to have it on a `list` (ie [ access.log, error.log ])?

More readable and for maintainability.

2017-01-10 12:17 UTC, upbeta01 commented
Rest of the codes -- are good to me :+1:

2017-01-10 12:24 UTC, upbeta01 commented
NOTE: The `logrotate` role dependency is using a minimum version of 2.1 and the base role https://github.com/juwai/ansible-role-laravel is written on a 1.9 version. Hopefully, no built-in variable is used on this `role` that's depreciated on 2.1 so things run smoothly.

Lastly, we might want to pin down the version of this external role (so servers new and old) can have a unified installation.

2017-01-11 01:31 UTC, mark-juwai commented on tasks/main.yml
> +    path: '/var/log/nginx/{{ application_name }}/*.log'
I don't think it's a bad idea. Nginx logrotate also uses wildcard, so we don't have to update playbook if there is any other log file comes.

2017-01-11 01:34 UTC, mark-juwai commented
There is no ansible version problem issue for now. Sure we can consistent it later if necessary.

The thumb up above means your approved the PR? 😄

2017-01-11 02:45 UTC, upbeta01 commented
@mark-juwai - Can we now start pinning versions for the external `role`? That was my last point on the NOTE section.

2017-01-11 02:47 UTC, mark-juwai commented
@upbeta01 OK, please advise how to do that.

2017-01-11 03:09 UTC, mark-juwai commented
I noticed most of our roles are written in `1.9.*`, I suggest to have a dedicated ticket to fix that. What do you think? @tjoelsson

2017-01-11 03:29 UTC, upbeta01 commented on meta/main.yml
> +  - { role: retr0h.logrotate, when: laravel_rotate_nginx_log }
`{ role: retr0h.logrotate,2.0, when: laravel_rotate_nginx_log }`

- should pin it to the `role` 2.0 version.

2017-01-11 03:34 UTC, mark-juwai commented on meta/main.yml
> +  - { role: retr0h.logrotate, when: laravel_rotate_nginx_log }
Their 2.0 version is not working well, we do need 2.0.1.

2017-01-11 03:40 UTC, tjoelsson commented
Are you guys referring to `min_ansible_version: 1.9` or what it says in the readme? We can update the min_ansible_version for sure. It should be 2.1.

2017-01-11 03:49 UTC, upbeta01 commented on meta/main.yml
> +  - { role: retr0h.logrotate, when: laravel_rotate_nginx_log }
Ok, if 2.0.1 is what we need. Then we should go with it.

2017-01-11 04:16 UTC, mark-juwai commented
@upbeta01 `min_ansible_version` updated.

2017-01-11 12:02 UTC, upbeta01 commented
Reviewed, all good. :+1:  (Approved)

2017-01-11 12:05 UTC, mark-juwai commented
```
ERROR! the role 'retr0h.logrotate,2.0.1' was not found in /Users/juwai/Projects/mobile-api-v2-ansible/roles:/Users/juwai/Projects/mobile-api-v2-ansible:/etc/ansible/roles:/Users/juwai/Projects/mobile-api-v2-ansible/roles
```
Still have error while running the role.

2017-01-11 12:12 UTC, upbeta01 commented
Let's skip pinning of version for now. Let's figure it out when we have time.

2017-01-11 12:15 UTC, mark-juwai commented
OK, thank you. @upbeta01 
I reverted my last commit. Still good? @upbeta01 @tjoelsson

2017-01-12 04:04 UTC, tjoelsson approved these changes

2017-01-12 04:09 UTC, merged