Dynamic CORS variables
juwai/ansible-role-laravel pull request #6
Opened 2017-01-19 06:48 UTC by mark-juwai

## Summary of changes

- Make the CORS variables configurable.

## How to Test

- Run `$ vagrant up`
- Run `$ vagrant ssh -c 'cat /etc/nginx/conf.d/test.conf'`, you can see CORS related config items `Access-Control-*` in the nginx config file.

2017-01-20 03:01 UTC, tjoelsson requested changes

2017-01-20 03:01 UTC, tjoelsson commented on README.md
> +Enable CORS, and specify allowded origin, Access-Control-Allow-Origin.
allowed

2017-01-20 03:01 UTC, tjoelsson commented on README.md
> +Whether or not allow credentials for CORS, Access-Control-Allow-Credentials.
Whether or not to allow...

2017-01-20 03:01 UTC, tjoelsson commented on templates/nginx.conf.j2
> -            return 204;
Will OPTIONS requests still return 204?

2017-01-20 03:03 UTC, mark-juwai commented on templates/nginx.conf.j2
> -            return 204;
No, it doesn't has to be 204, 200 also work.

2017-01-20 03:13 UTC, tjoelsson approved these changes

2017-01-23 02:31 UTC, agirivera reviewed
I have a non-blocking comment. Also not sure which vagrant box I need to provision to test.

2017-01-23 02:31 UTC, agirivera commented on tests/group_vars/all.yml
> +laravel_access_control_allow_methods: 'GET,POST,OPTIONS'
? Arrange the headers alphabetically so it will be easier to look for something in the future.

2017-01-23 02:38 UTC, mark-juwai commented
>I have a non-blocking comment. Also not sure which vagrant box I need to provision to test.

Running `vagrant up` under folder `tests` will create the vagrant box. Sorry for the unclear description, updated.

2017-01-23 03:21 UTC, mark-juwai commented
@agirivera Comment addressed, kindly have a look.

2017-01-23 03:57 UTC, agirivera approved these changes
All good :+1: Saw the relevant sections on the config file.

2017-01-23 03:58 UTC, mark-juwai commented
Still good? @tjoelsson

2017-01-23 04:01 UTC, tjoelsson approved these changes

2017-01-23 04:01 UTC, merged