[IND-376] Add SSL Certificate in admin.juwai.com
juwai/ansible-role-laravel pull request #7
Opened 2017-02-03 08:25 UTC by piadelosreyes

## Summary of changes

- _Add script to create SSL key and certificate_

## How to Test

- _Check if the SSL certs and key are same with
[AllCerts.includingadmin.zip](https://github.com/juwai/ansible-role-laravel/files/749768/AllCerts.includingadmin.zip)_

2017-02-06 04:08 UTC, tjoelsson requested changes

2017-02-06 04:08 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +    dest: "/etc/ssl/admin.juwai.com.crt"
Use variable

2017-02-06 04:08 UTC, tjoelsson commented on defaults/main.yml
> +laravel_https_enabled: 'on'
Let's make this variable a boolean (yes/no) so adding certificate files and using https is optional. Not all applications will need it, but should still be able to use this role.

2017-02-06 04:08 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +    mode: 0640
We only want root to able to read this file. 640 is only for a special case where PHP needs to read the file too.

2017-02-06 04:08 UTC, tjoelsson commented on templates/admin.juwai.com.crt.j2
> +{{ admin_juwai_com_crt }}{{ digicert_crt }}
Name of this file should be generic

2017-02-06 04:08 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +    mode: 0640
Also change the group to root.

2017-02-06 04:08 UTC, tjoelsson commented on templates/nginx.conf.j2
> +    ssl_certificate_key         {{ laravel_https_key }};
Wrap all these in an if-statement.

2017-02-06 04:11 UTC, tjoelsson commented on defaults/main.yml
> +laravel_https_enabled: 'on'
The default value should be no

2017-02-06 10:09 UTC, tjoelsson requested changes

2017-02-06 10:09 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +- name: create symlink so php saml library can find the key file
This symlink is not needed. It's only for SAML implementation.

2017-02-06 10:09 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +- name: create SSL certificate file
.sp file is also just for SAML. Can remove it.

2017-02-06 10:09 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +    mode: 0640
Change to 0600

2017-02-07 05:20 UTC, tjoelsson commented on defaults/main.yml
> +nginx_use_ssl: true
You can keep the name `laravel_https_enabled`. We want to have laravel_ as namespace for variables.

2017-02-07 06:50 UTC, tjoelsson requested changes
Add all new variables to readme

2017-02-07 06:50 UTC, tjoelsson commented on defaults/main.yml
> +laravel_https_enabled: true
default to false

2017-02-07 06:50 UTC, tjoelsson commented on templates/admin.juwai.com.crt.j2
> +{{ ssl_certs_crt }}{{ digicert_crt }}
Use a generic name for this file, like `ssl.crt.j2`

2017-02-07 06:50 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +    src: "{{ cert_source }}"
This should be the template file

2017-02-07 06:50 UTC, tjoelsson commented on tasks/main.yml
> +- include: ssl_certificate.yml
when laravel_https_enabled

2017-02-13 05:58 UTC, piadelosreyes commented
Hi @tjoelsson, this is now ready for your review again. thanks

2017-02-13 06:16 UTC, tjoelsson requested changes

2017-02-13 06:16 UTC, tjoelsson commented on tasks/main.yml
> +  when: laravel_https_enabled and (env == 'production' or env == 'staging')
No need to check environment here. The variable can be set for different environments in playbook inventory files.

2017-02-13 06:16 UTC, tjoelsson commented on templates/ssl.crt.j2
> +{{ ssl_certs_crt }}{{ digicert_crt }}
There are two more variables here. Need to document. Better use the same naming conventions for them as well.

These variables contain the actual certificate content. Maybe the path variables should end with _path.

2017-02-27 01:20 UTC, piadelosreyes commented
@tjoelsson please review again. thanks.

2017-02-27 02:47 UTC, tjoelsson commented on README.md
> +### laravel_https_digicert_data
Digicert is a company providing SSL certificates. Let's make this more generic and call it `laravel_https_chain_data`. Chain as in the certificate chain, which can include intermediate and root certificates.

2017-02-27 07:39 UTC, piadelosreyes commented on README.md
> +### laravel_https_digicert_data
renamed in 05369c4

2017-02-27 09:01 UTC, tjoelsson commented on tasks/ssl_certificate.yml
> +- name: create SSL + digicert certificate file
Just update this description and I think it's ok

2017-02-28 02:14 UTC, tjoelsson approved these changes

2017-02-28 02:23 UTC, mark-juwai approved these changes

2017-06-13 07:34 UTC, merged