[IND-376] Redirect site from http to https
juwai/ansible-role-laravel pull request #8
Opened 2017-06-13 08:52 UTC by piadelosreyes

## Summary of changes

- _Add new variable laravel_https_redirect and set to default `true`_

/fyi: @tjoelsson, @mark-juwai : Please review.

2017-06-13 09:01 UTC, tjoelsson commented on templates/nginx.conf.j2
> +    {%- endif %}
This needs to be in a separate `server {}` block listening to port 80

2017-06-13 09:45 UTC, piadelosreyes commented on templates/nginx.conf.j2
> +    {%- endif %}
I changed the https:// to $scheme:// as per https://www.digitalocean.com/community/questions/best-way-to-configure-nginx-ssl-force-http-to-redirect-to-https-force-www-to-non-www-on-serverpilot-free-plan-by-using-nginx-configuration-file-only

2017-06-13 10:14 UTC, tjoelsson commented on templates/nginx.conf.j2
> +    {%- endif %}
As described in the linked article, you need a separate server block:

```
server {
    listen 80;
    listen [::]:80;
    server_name example.com www.example.com; 
    return 301 https://example.com$request_uri;
}
```

2017-06-15 08:00 UTC, piadelosreyes commented
@tjoelsson please review. thanks

2017-06-15 08:37 UTC, tjoelsson commented on templates/nginx.conf.j2
> +{% if laravel_https_redirect -%}
Since laravel_https_redirect is enabled by default, better also check laravel_https_enabled here. Or make it disabled by default.

2017-06-15 08:49 UTC, piadelosreyes commented on templates/nginx.conf.j2
> +{% if laravel_https_redirect -%}
done https://github.com/juwai/ansible-role-laravel/pull/8/commits/034628c9bfe5a57a3df66f93a7a0219d81a3d844

2017-06-15 10:15 UTC, tjoelsson requested changes

2017-06-15 10:15 UTC, tjoelsson commented on templates/nginx.conf.j2
> +    listen         [::]:80;
? This is for ipv6, not sure it's required. We already have listen on port 80 above. Should be enough.

2017-06-15 10:15 UTC, tjoelsson commented on templates/nginx.conf.j2
> +    return         301 https://{{ server_name }}$request_uri;
Use `$host` instead of `{{ server_name }}`. The server_name variable can be a regex, while host is the one requested by browser.

2017-06-16 02:26 UTC, piadelosreyes commented on templates/nginx.conf.j2
> +    listen         [::]:80;
ok. I removed it.

2017-06-16 02:27 UTC, piadelosreyes commented on templates/nginx.conf.j2
> +    return         301 https://{{ server_name }}$request_uri;
Updated https://github.com/juwai/ansible-role-laravel/pull/8/commits/82e3cc3bd129725a39efc6890c72f25af303a56d. thanks

2017-06-16 02:39 UTC, tjoelsson approved these changes

2017-06-16 02:48 UTC, kevinfelisilda approved these changes

2017-06-16 02:49 UTC, kevinfelisilda commented
? just want to ask, the `laravel_https_redirect` will also be set in each repo right? for instance in prod env, we are setting this to true.

2017-06-16 02:50 UTC, piadelosreyes commented
@kevinfelisilda yes, please see https://github.com/juwai/redkeep/pull/177/files#diff-4b70a5d39bc162811b48bfdc0aef7279R11

2017-06-16 02:51 UTC, kevinfelisilda commented
alright, cool.. thanks @piadelosreyes

2017-06-16 05:19 UTC, merged